### ISSUE TITLE
Compare debug_ and trace_*

### ISSUE THREAD

**Issue by trmaphi** [Octan-Labs/pipeline#158]
README compare trace vs debug namespace. Chỉ nhắm đến cái method nào có thể query trace/debug theo block range

Background là hiện tại có 2 implementation của EVM là geth và erigon. Supports cho nó thì hiện tại geth có debug_* và erigon có debug_* và trace_*

Erigon đang drop support cho BSC, nên trong tương lai có thể phải switch qua debug_* cho indexer. Nên cần map data từ trace_filter method > debug_* mẹthod gì đó tương ứng

**Comment by tuannm1006** [comment]
Methods usage:

- Geth: debug_traceBlockByNumber
- Parity: trace_block

Differences between geth and parity traces:

- **geth** output doesn't have **_reward_** traces.
- **geth** output doesn't have **_to_address_**, **_from_address_** and **_value_** for **_suicide_** traces.
- **geth** output doesn't have **_traceAddress_**, **_transactionHash_** and **_transactionPosition_**.
- **geth** output doesn't have **_reward_** traces.

Both exporting geth traces and exporting parity traces are supported by indexer, but generate trace id function depend on transaction hash and transaction index. Indexer export_all is using exporting parity traces now.

References:

- Using geth trace: [polygon-etl](https://github.com/blockchain-etl/polygon-etl/blob/HEAD/cli/polygonetl/streaming/eth_streamer_adapter.py#L61-L65)
- Using parity trace: [etherum-etl](https://github.com/blockchain-etl/ethereum-etl/blob/HEAD/ethereumetl/streaming/eth_streamer_adapter.py#L59-L62)
