### ISSUE TITLE
[Clickhouse] Cannot remove duplicated data  

### ISSUE THREAD

**Issue by tuannm1006** [Octan-Labs/pipeline#165]
Cannot use [OPTIMIZE Statement](https://clickhouse.com/docs/en/sql-reference/statements/optimize) to remove duplicate data from tables with **ReplicatedReplacingMergeTree** engine.
* Executing `OPTIMIZE TABLE bsc_trace DEDUPLICATE` updates 0 row in bsc_block table.
* Query `SELECT COUNT(*) from bsc_trace` and `SELECT COUNT(*) from bsc_trace FINAL` has different result.

**Comment by trmaphi** [comment]
Use on Cluster clause @tuannm1006

**Comment by trmaphi** [comment]
```
OPTIMIZE TABLE default.bsc_trace FINAL DEDUPLICATE BY block_number, trace_id, trace_index, block_timestamp
    SETTINGS optimize_skip_merged_partitions=1, optimize_throw_if_noop=1, alter_sync=2;
```
