### ISSUE TITLE
Global Reputation Score Analysis(EOA Group) table & chart

### ISSUE THREAD

**Issue by noobmdev** [Octan-Labs/pipeline#191]
- [x] Total EOAs
- [x] Total EOAs with zero-GRS
- [x] Average Score: Reputation, Total Transfer, Total Receive, In Degree, Out Degree, Total Volume, Total Gas Spent (ETH)
- [x] Variance: Reputation, Total Transfer, Total Receive, In Degree, Out Degree, Total Volume, Total Gas Spent (ETH)
- [x] GRS histogram of non-zero EOA group
- [ ] Reputation Distribution of 6 partitions for non-zero EOA group

**Comment by longthanhta** [comment]
First step: Long will estimate the split point for each partition (in the data calculation till 010823, this already has been done)
+ Highest partition: Rank 1->41
+ High partition: Rank 42-> 61
+ Experience partition: Rank: 62->7444241
+ Medium partition: Rank: 7444242 -> 28937411
+ Low partition: Rank: 28937412 -> 31461554
+ Lowest partition: Rank: 31461555 -> 

Second step: The same as the global Reputation Score overview, get indegree, out-degree, total receive, and total transfer for each address (For now Long will calculate, later this could be done in the pipeline)

Third step: Then calculate mean and variance for each group: highest, high...
