### ISSUE TITLE
Global Reputation Score Overview

### ISSUE THREAD

**Issue by noobmdev** [Octan-Labs/pipeline#193]
- [x] Average score of all addresses/contracts/EOAs table
- [x] Variance of all addresses/contracts/EOAs table

**Comment by longthanhta** [comment]
Procedure to calculate this:
Step 1: Calculate Total Transfer, Total Receive, In Degree, Out Degree, Total Volume, and Total Gas Spent for all addresses.
           + Total gas spent here is for all "TXN out"
Step 2: Merge with contract list (Contract and Address are in reputation_score_table) and filter to:
            + all addresses
            +  contract only
            + EOA only
Step 3: Calculate mean and variance for :
            + Reputation 
            + Total Transfer 
            + Total Receive
            + In Degree
            + Out Degree
            + Total Volume
            + Total Gas Spent

**Comment by longthanhta** [comment]
SELECT
    'All addresses' AS categories,
    AVG(reputation_score) AS reputation_score,
    AVG(total_transfer) AS total_transfer,
    AVG(total_receive) AS total_receive,
    AVG(in_degree) AS in_degree,
    AVG(out_degree) AS out_degree,
    AVG(total_volume) AS total_volume,
    AVG(total_gas_spent) AS total_gas_spent
FROM
    eth_reputation_score rs
WHERE
	rs.snapshot_block_number=17823594
UNION ALL
SELECT
    'Contracts' AS categories,
    AVG(reputation_score) AS reputation_score,
    AVG(total_transfer) AS total_transfer,
    AVG(total_receive) AS total_receive,
    AVG(in_degree) AS in_degree,
    AVG(out_degree) AS out_degree,
    AVG(total_volume) AS total_volume,
    AVG(total_gas_spent) AS total_gas_spent
FROM
    eth_reputation_score rs
WHERE
    rs.contract = True
AND
	rs.snapshot_block_number=17823594
UNION ALL
SELECT
    'EOAs' AS categories,
    AVG(reputation_score) AS reputation_score,
    AVG(total_transfer) AS total_transfer,
    AVG(total_receive) AS total_receive,
    AVG(in_degree) AS in_degree,
    AVG(out_degree) AS out_degree,
    AVG(total_volume) AS total_volume,
    AVG(total_gas_spent) AS total_gas_spent
FROM
    eth_reputation_score rs
WHERE
    rs.contract = False
AND
	rs.snapshot_block_number=17823594
