### ISSUE TITLE
Parquet file partition rewrite

### ISSUE THREAD

**Issue by trmaphi** [Octan-Labs/pipeline#41]
Currently, partitions are breakdown into hours to ensure export is complete and minimize delay with on chain. But diving parquet file into small data is not good practice. 

- [ ] Write a spark job to merge hour partition data to date partition (start from 2021-02-09)
- [ ] Verify data

**Comment by tuannm1006** [comment]
Still got error on key permission

**Comment by trmaphi** [comment]
Resolve https://github.com/Octan-Labs/pipeline/issues/75
