### ISSUE TITLE
Compare CMC top token with bsc, coingeko

### ISSUE THREAD

**Issue by trmaphi** [Octan-Labs/pipeline#74]

**Comment by trmaphi** [comment]
nếu check bằng address mình crawl được thì có 372 token trên top 500 bscscan xuất hiện trong top 10000 CMC, 346 token cho top 5000  CMC
nếu check bằng token (có thể bị trùng) thì có đủ 500 token xuất hiện trong top 10000 CMC, 450 token trong top 5000 CMC

**Comment by longthanhta** [comment]
Figure: https://drive.google.com/file/d/1nVtG6XA32PTC3imekCRyB15paRsWXFco/view?usp=drive_link
View online: https://whimsical.com/data-flow-jul-2023-BKiyTbWebi9oXZKekFd6Hz@2Ux7TurymMVGkr1R9FSa
